// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AbilityScalarType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum AbilityScalarType
 */
export declare enum AbilityScalarType {
    /**
     * @generated from protobuf enum value: UNKNOW = 0;
     */
    UNKNOW = 0,
    /**
     * @generated from protobuf enum value: FLOAT = 1;
     */
    FLOAT = 1,
    /**
     * @generated from protobuf enum value: INT = 2;
     */
    INT = 2,
    /**
     * @generated from protobuf enum value: BOOL = 3;
     */
    BOOL = 3,
    /**
     * @generated from protobuf enum value: TRIGGER = 4;
     */
    TRIGGER = 4,
    /**
     * @generated from protobuf enum value: STRING = 5;
     */
    STRING = 5,
    /**
     * @generated from protobuf enum value: UINT = 6;
     */
    UINT = 6
}
