// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "AbilityEmbryo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AbilityEmbryo
 */
export interface AbilityEmbryo {
    /**
     * @generated from protobuf field: uint32 ability_id = 1;
     */
    abilityId: number;
    /**
     * @generated from protobuf field: fixed32 ability_name_hash = 2;
     */
    abilityNameHash: number;
    /**
     * @generated from protobuf field: fixed32 ability_override_name_hash = 3;
     */
    abilityOverrideNameHash: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class AbilityEmbryo$Type extends MessageType<AbilityEmbryo> {
    constructor() {
        super("AbilityEmbryo", [
            { no: 1, name: "ability_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "ability_name_hash", kind: "scalar", T: 7 /*ScalarType.FIXED32*/ },
            { no: 3, name: "ability_override_name_hash", kind: "scalar", T: 7 /*ScalarType.FIXED32*/ }
        ]);
    }
    create(value?: PartialMessage<AbilityEmbryo>): AbilityEmbryo {
        const message = { abilityId: 0, abilityNameHash: 0, abilityOverrideNameHash: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AbilityEmbryo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AbilityEmbryo): AbilityEmbryo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 ability_id */ 1:
                    message.abilityId = reader.uint32();
                    break;
                case /* fixed32 ability_name_hash */ 2:
                    message.abilityNameHash = reader.fixed32();
                    break;
                case /* fixed32 ability_override_name_hash */ 3:
                    message.abilityOverrideNameHash = reader.fixed32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AbilityEmbryo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 ability_id = 1; */
        if (message.abilityId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.abilityId);
        /* fixed32 ability_name_hash = 2; */
        if (message.abilityNameHash !== 0)
            writer.tag(2, WireType.Bit32).fixed32(message.abilityNameHash);
        /* fixed32 ability_override_name_hash = 3; */
        if (message.abilityOverrideNameHash !== 0)
            writer.tag(3, WireType.Bit32).fixed32(message.abilityOverrideNameHash);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AbilityEmbryo
 */
export const AbilityEmbryo = new AbilityEmbryo$Type();
