// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "AbilityControlBlock.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AbilityEmbryo } from "./AbilityEmbryo";
/**
 * @generated from protobuf message AbilityControlBlock
 */
export interface AbilityControlBlock {
    /**
     * @generated from protobuf field: repeated AbilityEmbryo ability_embryo_list = 1;
     */
    abilityEmbryoList: AbilityEmbryo[];
}
// @generated message type with reflection information, may provide speed optimized methods
class AbilityControlBlock$Type extends MessageType<AbilityControlBlock> {
    constructor() {
        super("AbilityControlBlock", [
            { no: 1, name: "ability_embryo_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AbilityEmbryo }
        ]);
    }
    create(value?: PartialMessage<AbilityControlBlock>): AbilityControlBlock {
        const message = { abilityEmbryoList: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AbilityControlBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AbilityControlBlock): AbilityControlBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated AbilityEmbryo ability_embryo_list */ 1:
                    message.abilityEmbryoList.push(AbilityEmbryo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AbilityControlBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated AbilityEmbryo ability_embryo_list = 1; */
        for (let i = 0; i < message.abilityEmbryoList.length; i++)
            AbilityEmbryo.internalBinaryWrite(message.abilityEmbryoList[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AbilityControlBlock
 */
export const AbilityControlBlock = new AbilityControlBlock$Type();
