// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AdjustTrackingInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AdjustTrackingInfo
 */
export interface AdjustTrackingInfo {
    /**
     * @generated from protobuf field: string idfa = 1;
     */
    idfa: string;
    /**
     * @generated from protobuf field: string gps_adid = 2;
     */
    gpsAdid: string;
    /**
     * @generated from protobuf field: string fire_adid = 3;
     */
    fireAdid: string;
    /**
     * @generated from protobuf field: string adid = 4;
     */
    adid: string;
    /**
     * @generated from protobuf field: string event_token = 5;
     */
    eventToken: string;
    /**
     * @generated from protobuf field: string app_token = 6;
     */
    appToken: string;
}
declare class AdjustTrackingInfo$Type extends MessageType<AdjustTrackingInfo> {
    constructor();
    create(value?: PartialMessage<AdjustTrackingInfo>): AdjustTrackingInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AdjustTrackingInfo): AdjustTrackingInfo;
    internalBinaryWrite(message: AdjustTrackingInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message AdjustTrackingInfo
 */
export declare const AdjustTrackingInfo: AdjustTrackingInfo$Type;
export {};
