// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarExpeditionState.proto" (syntax proto3),// tslint:disable
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarExpeditionState.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum AvatarExpeditionState
 */
export var AvatarExpeditionState;
(function (AvatarExpeditionState) {
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_NONE = 0;
     */
    AvatarExpeditionState[AvatarExpeditionState["AVATAR_EXPEDITION_NONE"] = 0] = "AVATAR_EXPEDITION_NONE";
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_DOING = 1;
     */
    AvatarExpeditionState[AvatarExpeditionState["AVATAR_EXPEDITION_DOING"] = 1] = "AVATAR_EXPEDITION_DOING";
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_FINISH_WAIT_REWARD = 2;
     */
    AvatarExpeditionState[AvatarExpeditionState["AVATAR_EXPEDITION_FINISH_WAIT_REWARD"] = 2] = "AVATAR_EXPEDITION_FINISH_WAIT_REWARD";
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD = 3;
     */
    AvatarExpeditionState[AvatarExpeditionState["AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD"] = 3] = "AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD";
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_LOCKED = 4;
     */
    AvatarExpeditionState[AvatarExpeditionState["AVATAR_EXPEDITION_LOCKED"] = 4] = "AVATAR_EXPEDITION_LOCKED";
})(AvatarExpeditionState || (AvatarExpeditionState = {}));
