// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarEquipAffixInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AvatarEquipAffixInfo
 */
export interface AvatarEquipAffixInfo {
    /**
     * @generated from protobuf field: uint32 equip_affix_id = 1;
     */
    equipAffixId: number;
    /**
     * @generated from protobuf field: uint32 left_cd_time = 2;
     */
    leftCdTime: number;
}
declare class AvatarEquipAffixInfo$Type extends MessageType<AvatarEquipAffixInfo> {
    constructor();
    create(value?: PartialMessage<AvatarEquipAffixInfo>): AvatarEquipAffixInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvatarEquipAffixInfo): AvatarEquipAffixInfo;
    internalBinaryWrite(message: AvatarEquipAffixInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message AvatarEquipAffixInfo
 */
export declare const AvatarEquipAffixInfo: AvatarEquipAffixInfo$Type;
export {};
