// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "AvatarExpeditionState.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum AvatarExpeditionState
 */
export enum AvatarExpeditionState {
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_NONE = 0;
     */
    AVATAR_EXPEDITION_NONE = 0,
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_DOING = 1;
     */
    AVATAR_EXPEDITION_DOING = 1,
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_FINISH_WAIT_REWARD = 2;
     */
    AVATAR_EXPEDITION_FINISH_WAIT_REWARD = 2,
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD = 3;
     */
    AVATAR_EXPEDITION_CALLBACK_WAIT_REWARD = 3,
    /**
     * @generated from protobuf enum value: AVATAR_EXPEDITION_LOCKED = 4;
     */
    AVATAR_EXPEDITION_LOCKED = 4
}
