// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarEnterSceneInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ServerBuff } from "./ServerBuff";
import { AbilitySyncStateInfo } from "./AbilitySyncStateInfo";
/**
 * @generated from protobuf message AvatarEnterSceneInfo
 */
export interface AvatarEnterSceneInfo {
    /**
     * @generated from protobuf field: uint64 avatar_guid = 1;
     */
    avatarGuid: bigint;
    /**
     * @generated from protobuf field: uint32 avatar_entity_id = 2;
     */
    avatarEntityId: number;
    /**
     * @generated from protobuf field: AbilitySyncStateInfo avatar_ability_info = 3;
     */
    avatarAbilityInfo?: AbilitySyncStateInfo;
    /**
     * @generated from protobuf field: repeated uint32 buff_id_list = 4;
     */
    buffIdList: number[];
    /**
     * @generated from protobuf field: uint64 weapon_guid = 5;
     */
    weaponGuid: bigint;
    /**
     * @generated from protobuf field: uint32 weapon_entity_id = 6;
     */
    weaponEntityId: number;
    /**
     * @generated from protobuf field: AbilitySyncStateInfo weapon_ability_info = 7;
     */
    weaponAbilityInfo?: AbilitySyncStateInfo;
    /**
     * @generated from protobuf field: repeated ServerBuff server_buff_list = 8;
     */
    serverBuffList: ServerBuff[];
}
declare class AvatarEnterSceneInfo$Type extends MessageType<AvatarEnterSceneInfo> {
    constructor();
    create(value?: PartialMessage<AvatarEnterSceneInfo>): AvatarEnterSceneInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvatarEnterSceneInfo): AvatarEnterSceneInfo;
    internalBinaryWrite(message: AvatarEnterSceneInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message AvatarEnterSceneInfo
 */
export declare const AvatarEnterSceneInfo: AvatarEnterSceneInfo$Type;
export {};
