// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarExcelInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AvatarExcelInfo
 */
export interface AvatarExcelInfo {
    /**
     * @generated from protobuf field: uint64 prefab_path_hash = 1;
     */
    prefabPathHash: bigint;
    /**
     * @generated from protobuf field: uint64 prefab_path_remote_hash = 2;
     */
    prefabPathRemoteHash: bigint;
    /**
     * @generated from protobuf field: uint64 controller_path_hash = 3;
     */
    controllerPathHash: bigint;
    /**
     * @generated from protobuf field: uint64 controller_path_remote_hash = 4;
     */
    controllerPathRemoteHash: bigint;
    /**
     * @generated from protobuf field: uint64 combat_config_hash = 5;
     */
    combatConfigHash: bigint;
}
declare class AvatarExcelInfo$Type extends MessageType<AvatarExcelInfo> {
    constructor();
    create(value?: PartialMessage<AvatarExcelInfo>): AvatarExcelInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvatarExcelInfo): AvatarExcelInfo;
    internalBinaryWrite(message: AvatarExcelInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message AvatarExcelInfo
 */
export declare const AvatarExcelInfo: AvatarExcelInfo$Type;
export {};
