// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "AvatarDataNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AvatarTeam } from "./AvatarTeam";
import { AvatarInfo } from "./AvatarInfo";
/**
 * @generated from protobuf message AvatarDataNotify
 */
export interface AvatarDataNotify {
    /**
     * @generated from protobuf field: repeated AvatarInfo avatar_list = 1;
     */
    avatarList: AvatarInfo[];
    /**
     * @generated from protobuf field: map<uint32, AvatarTeam> avatar_team_map = 2;
     */
    avatarTeamMap: {
        [key: number]: AvatarTeam;
    };
    /**
     * @generated from protobuf field: uint32 cur_avatar_team_id = 3;
     */
    curAvatarTeamId: number;
    /**
     * @generated from protobuf field: uint64 choose_avatar_guid = 4;
     */
    chooseAvatarGuid: bigint;
    /**
     * @generated from protobuf field: repeated uint64 temp_avatar_guid_list = 5;
     */
    tempAvatarGuidList: bigint[];
    /**
     * @generated from protobuf field: repeated uint32 owned_flycloak_list = 6;
     */
    ownedFlycloakList: number[];
    /**
     * @generated from protobuf field: repeated uint32 owned_costume_list = 7;
     */
    ownedCostumeList: number[];
}
/**
 * @generated from protobuf enum AvatarDataNotify.CmdId
 */
export declare enum AvatarDataNotify_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 1694;
     */
    CMD_ID = 1694
}
declare class AvatarDataNotify$Type extends MessageType<AvatarDataNotify> {
    constructor();
    create(value?: PartialMessage<AvatarDataNotify>): AvatarDataNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvatarDataNotify): AvatarDataNotify;
    private binaryReadMap2;
    internalBinaryWrite(message: AvatarDataNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message AvatarDataNotify
 */
export declare const AvatarDataNotify: AvatarDataNotify$Type;
export {};
