// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "BlossomChestInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message BlossomChestInfo
 */
export interface BlossomChestInfo {
    /**
     * @generated from protobuf field: uint32 resin = 1;
     */
    resin: number;
    /**
     * @generated from protobuf field: repeated uint32 qualify_uid_list = 2;
     */
    qualifyUidList: number[];
    /**
     * @generated from protobuf field: repeated uint32 remain_uid_list = 3;
     */
    remainUidList: number[];
    /**
     * @generated from protobuf field: uint32 dead_time = 4;
     */
    deadTime: number;
    /**
     * @generated from protobuf field: uint32 blossom_refresh_type = 5;
     */
    blossomRefreshType: number;
    /**
     * @generated from protobuf field: uint32 refresh_id = 6;
     */
    refreshId: number;
}
declare class BlossomChestInfo$Type extends MessageType<BlossomChestInfo> {
    constructor();
    create(value?: PartialMessage<BlossomChestInfo>): BlossomChestInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlossomChestInfo): BlossomChestInfo;
    internalBinaryWrite(message: BlossomChestInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message BlossomChestInfo
 */
export declare const BlossomChestInfo: BlossomChestInfo$Type;
export {};
