// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "ClientGadgetInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ClientGadgetInfo
 */
export interface ClientGadgetInfo {
    /**
     * @generated from protobuf field: uint32 camp_id = 1;
     */
    campId: number;
    /**
     * @generated from protobuf field: uint32 camp_type = 2;
     */
    campType: number;
    /**
     * @generated from protobuf field: uint64 guid = 3;
     */
    guid: bigint;
    /**
     * @generated from protobuf field: uint32 owner_entity_id = 4;
     */
    ownerEntityId: number;
    /**
     * @generated from protobuf field: uint32 target_entity_id = 5;
     */
    targetEntityId: number;
    /**
     * @generated from protobuf field: bool async_load = 6;
     */
    asyncLoad: boolean;
}
declare class ClientGadgetInfo$Type extends MessageType<ClientGadgetInfo> {
    constructor();
    create(value?: PartialMessage<ClientGadgetInfo>): ClientGadgetInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientGadgetInfo): ClientGadgetInfo;
    internalBinaryWrite(message: ClientGadgetInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message ClientGadgetInfo
 */
export declare const ClientGadgetInfo: ClientGadgetInfo$Type;
export {};
