// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "CurVehicleInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CurVehicleInfo
 */
export interface CurVehicleInfo {
    /**
     * @generated from protobuf field: uint32 entity_id = 1;
     */
    entityId: number;
    /**
     * @generated from protobuf field: uint32 pos = 2;
     */
    pos: number;
}
declare class CurVehicleInfo$Type extends MessageType<CurVehicleInfo> {
    constructor();
    create(value?: PartialMessage<CurVehicleInfo>): CurVehicleInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CurVehicleInfo): CurVehicleInfo;
    internalBinaryWrite(message: CurVehicleInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message CurVehicleInfo
 */
export declare const CurVehicleInfo: CurVehicleInfo$Type;
export {};
