// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "EchoShellInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message EchoShellInfo
 */
export interface EchoShellInfo {
    /**
     * @generated from protobuf field: uint32 shell_id = 1;
     */
    shellId: number;
}
declare class EchoShellInfo$Type extends MessageType<EchoShellInfo> {
    constructor();
    create(value?: PartialMessage<EchoShellInfo>): EchoShellInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EchoShellInfo): EchoShellInfo;
    internalBinaryWrite(message: EchoShellInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message EchoShellInfo
 */
export declare const EchoShellInfo: EchoShellInfo$Type;
export {};
