"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnterType = void 0;
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "EnterType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum EnterType
 */
var EnterType;
(function (EnterType) {
    /**
     * @generated from protobuf enum value: ENTER_NONE = 0;
     */
    EnterType[EnterType["ENTER_NONE"] = 0] = "ENTER_NONE";
    /**
     * @generated from protobuf enum value: ENTER_SELF = 1;
     */
    EnterType[EnterType["ENTER_SELF"] = 1] = "ENTER_SELF";
    /**
     * @generated from protobuf enum value: ENTER_GOTO = 2;
     */
    EnterType[EnterType["ENTER_GOTO"] = 2] = "ENTER_GOTO";
    /**
     * @generated from protobuf enum value: ENTER_JUMP = 3;
     */
    EnterType[EnterType["ENTER_JUMP"] = 3] = "ENTER_JUMP";
    /**
     * @generated from protobuf enum value: ENTER_OTHER = 4;
     */
    EnterType[EnterType["ENTER_OTHER"] = 4] = "ENTER_OTHER";
    /**
     * @generated from protobuf enum value: ENTER_BACK = 5;
     */
    EnterType[EnterType["ENTER_BACK"] = 5] = "ENTER_BACK";
    /**
     * @generated from protobuf enum value: ENTER_DUNGEON = 6;
     */
    EnterType[EnterType["ENTER_DUNGEON"] = 6] = "ENTER_DUNGEON";
    /**
     * @generated from protobuf enum value: ENTER_DUNGEON_REPLAY = 7;
     */
    EnterType[EnterType["ENTER_DUNGEON_REPLAY"] = 7] = "ENTER_DUNGEON_REPLAY";
    /**
     * @generated from protobuf enum value: ENTER_GOTO_BY_PORTAL = 8;
     */
    EnterType[EnterType["ENTER_GOTO_BY_PORTAL"] = 8] = "ENTER_GOTO_BY_PORTAL";
    /**
     * @generated from protobuf enum value: ENTER_SELF_HOME = 9;
     */
    EnterType[EnterType["ENTER_SELF_HOME"] = 9] = "ENTER_SELF_HOME";
    /**
     * @generated from protobuf enum value: ENTER_OTHER_HOME = 10;
     */
    EnterType[EnterType["ENTER_OTHER_HOME"] = 10] = "ENTER_OTHER_HOME";
    /**
     * @generated from protobuf enum value: ENTER_GOTO_RECREATE = 11;
     */
    EnterType[EnterType["ENTER_GOTO_RECREATE"] = 11] = "ENTER_GOTO_RECREATE";
})(EnterType = exports.EnterType || (exports.EnterType = {}));
