// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "EnterSceneReadyReq.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message EnterSceneReadyReq
 */
export interface EnterSceneReadyReq {
    /**
     * @generated from protobuf field: uint32 enter_scene_token = 1;
     */
    enterSceneToken: number;
}
/**
 * @generated from protobuf enum EnterSceneReadyReq.CmdId
 */
export declare enum EnterSceneReadyReq_CmdId {
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    IS_ALLOW_CLIENT = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 265;
     */
    CMD_ID = 265
}
declare class EnterSceneReadyReq$Type extends MessageType<EnterSceneReadyReq> {
    constructor();
    create(value?: PartialMessage<EnterSceneReadyReq>): EnterSceneReadyReq;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnterSceneReadyReq): EnterSceneReadyReq;
    internalBinaryWrite(message: EnterSceneReadyReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message EnterSceneReadyReq
 */
export declare const EnterSceneReadyReq: EnterSceneReadyReq$Type;
export {};
