// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "EnterSceneReadyRsp.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message EnterSceneReadyRsp
 */
export interface EnterSceneReadyRsp {
    /**
     * @generated from protobuf field: int32 retcode = 1;
     */
    retcode: number;
    /**
     * @generated from protobuf field: uint32 enter_scene_token = 2;
     */
    enterSceneToken: number;
}
/**
 * @generated from protobuf enum EnterSceneReadyRsp.CmdId
 */
export declare enum EnterSceneReadyRsp_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 245;
     */
    CMD_ID = 245
}
declare class EnterSceneReadyRsp$Type extends MessageType<EnterSceneReadyRsp> {
    constructor();
    create(value?: PartialMessage<EnterSceneReadyRsp>): EnterSceneReadyRsp;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnterSceneReadyRsp): EnterSceneReadyRsp;
    internalBinaryWrite(message: EnterSceneReadyRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message EnterSceneReadyRsp
 */
export declare const EnterSceneReadyRsp: EnterSceneReadyRsp$Type;
export {};
