// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "EntityAuthorityInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AnimatorParameterValueInfoPair } from "./AnimatorParameterValueInfoPair";
import { Vector } from "./Vector";
import { SceneEntityAiInfo } from "./SceneEntityAiInfo";
import { EntityRendererChangedInfo } from "./EntityRendererChangedInfo";
import { AbilitySyncStateInfo } from "./AbilitySyncStateInfo";
/**
 * @generated from protobuf message EntityAuthorityInfo
 */
export interface EntityAuthorityInfo {
    /**
     * @generated from protobuf field: AbilitySyncStateInfo ability_info = 1;
     */
    abilityInfo?: AbilitySyncStateInfo;
    /**
     * @generated from protobuf field: EntityRendererChangedInfo renderer_changed_info = 2;
     */
    rendererChangedInfo?: EntityRendererChangedInfo;
    /**
     * @generated from protobuf field: SceneEntityAiInfo ai_info = 3;
     */
    aiInfo?: SceneEntityAiInfo;
    /**
     * @generated from protobuf field: Vector born_pos = 4;
     */
    bornPos?: Vector;
    /**
     * @generated from protobuf field: repeated AnimatorParameterValueInfoPair pose_para_list = 5;
     */
    poseParaList: AnimatorParameterValueInfoPair[];
}
// @generated message type with reflection information, may provide speed optimized methods
class EntityAuthorityInfo$Type extends MessageType<EntityAuthorityInfo> {
    constructor() {
        super("EntityAuthorityInfo", [
            { no: 1, name: "ability_info", kind: "message", T: () => AbilitySyncStateInfo },
            { no: 2, name: "renderer_changed_info", kind: "message", T: () => EntityRendererChangedInfo },
            { no: 3, name: "ai_info", kind: "message", T: () => SceneEntityAiInfo },
            { no: 4, name: "born_pos", kind: "message", T: () => Vector },
            { no: 5, name: "pose_para_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AnimatorParameterValueInfoPair }
        ]);
    }
    create(value?: PartialMessage<EntityAuthorityInfo>): EntityAuthorityInfo {
        const message = { poseParaList: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<EntityAuthorityInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityAuthorityInfo): EntityAuthorityInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* AbilitySyncStateInfo ability_info */ 1:
                    message.abilityInfo = AbilitySyncStateInfo.internalBinaryRead(reader, reader.uint32(), options, message.abilityInfo);
                    break;
                case /* EntityRendererChangedInfo renderer_changed_info */ 2:
                    message.rendererChangedInfo = EntityRendererChangedInfo.internalBinaryRead(reader, reader.uint32(), options, message.rendererChangedInfo);
                    break;
                case /* SceneEntityAiInfo ai_info */ 3:
                    message.aiInfo = SceneEntityAiInfo.internalBinaryRead(reader, reader.uint32(), options, message.aiInfo);
                    break;
                case /* Vector born_pos */ 4:
                    message.bornPos = Vector.internalBinaryRead(reader, reader.uint32(), options, message.bornPos);
                    break;
                case /* repeated AnimatorParameterValueInfoPair pose_para_list */ 5:
                    message.poseParaList.push(AnimatorParameterValueInfoPair.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EntityAuthorityInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* AbilitySyncStateInfo ability_info = 1; */
        if (message.abilityInfo)
            AbilitySyncStateInfo.internalBinaryWrite(message.abilityInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* EntityRendererChangedInfo renderer_changed_info = 2; */
        if (message.rendererChangedInfo)
            EntityRendererChangedInfo.internalBinaryWrite(message.rendererChangedInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* SceneEntityAiInfo ai_info = 3; */
        if (message.aiInfo)
            SceneEntityAiInfo.internalBinaryWrite(message.aiInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* Vector born_pos = 4; */
        if (message.bornPos)
            Vector.internalBinaryWrite(message.bornPos, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated AnimatorParameterValueInfoPair pose_para_list = 5; */
        for (let i = 0; i < message.poseParaList.length; i++)
            AnimatorParameterValueInfoPair.internalBinaryWrite(message.poseParaList[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message EntityAuthorityInfo
 */
export const EntityAuthorityInfo = new EntityAuthorityInfo$Type();
