// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "FoundationStatus.proto" (syntax proto3),// tslint:disable
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "FoundationStatus.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum FoundationStatus
 */
export var FoundationStatus;
(function (FoundationStatus) {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    FoundationStatus[FoundationStatus["NONE"] = 0] = "NONE";
    /**
     * @generated from protobuf enum value: INIT = 1;
     */
    FoundationStatus[FoundationStatus["INIT"] = 1] = "INIT";
    /**
     * @generated from protobuf enum value: BUILDING = 2;
     */
    FoundationStatus[FoundationStatus["BUILDING"] = 2] = "BUILDING";
    /**
     * @generated from protobuf enum value: BUILT = 3;
     */
    FoundationStatus[FoundationStatus["BUILT"] = 3] = "BUILT";
})(FoundationStatus || (FoundationStatus = {}));
