// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "FriendEnterHomeOption.proto" (syntax proto3),// tslint:disable
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "FriendEnterHomeOption.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum FriendEnterHomeOption
 */
export var FriendEnterHomeOption;
(function (FriendEnterHomeOption) {
    /**
     * @generated from protobuf enum value: NEED_CONFIRM = 0;
     */
    FriendEnterHomeOption[FriendEnterHomeOption["NEED_CONFIRM"] = 0] = "NEED_CONFIRM";
    /**
     * @generated from protobuf enum value: REFUSE = 1;
     */
    FriendEnterHomeOption[FriendEnterHomeOption["REFUSE"] = 1] = "REFUSE";
    /**
     * @generated from protobuf enum value: DIRECT = 2;
     */
    FriendEnterHomeOption[FriendEnterHomeOption["DIRECT"] = 2] = "DIRECT";
})(FriendEnterHomeOption || (FriendEnterHomeOption = {}));
