// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "FriendOnlineState.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum FriendOnlineState
 */
export declare enum FriendOnlineState {
    /**
     * @generated from protobuf enum value: FREIEND_DISCONNECT = 0;
     */
    FREIEND_DISCONNECT = 0,
    /**
     * @generated from protobuf enum value: FRIEND_ONLINE = 1;
     */
    FRIEND_ONLINE = 1
}
