"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FriendOnlineState = void 0;
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "FriendOnlineState.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum FriendOnlineState
 */
var FriendOnlineState;
(function (FriendOnlineState) {
    /**
     * @generated from protobuf enum value: FREIEND_DISCONNECT = 0;
     */
    FriendOnlineState[FriendOnlineState["FREIEND_DISCONNECT"] = 0] = "FREIEND_DISCONNECT";
    /**
     * @generated from protobuf enum value: FRIEND_ONLINE = 1;
     */
    FriendOnlineState[FriendOnlineState["FRIEND_ONLINE"] = 1] = "FRIEND_ONLINE";
})(FriendOnlineState = exports.FriendOnlineState || (exports.FriendOnlineState = {}));
