// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "Furniture.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Furniture
 */
export interface Furniture {
    /**
     * @generated from protobuf field: uint32 count = 1;
     */
    count: number;
}
declare class Furniture$Type extends MessageType<Furniture> {
    constructor();
    create(value?: PartialMessage<Furniture>): Furniture;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Furniture): Furniture;
    internalBinaryWrite(message: Furniture, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message Furniture
 */
export declare const Furniture: Furniture$Type;
export {};
