// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "GadgetBornType.proto" (syntax proto3),// tslint:disable
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "GadgetBornType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum GadgetBornType
 */
export var GadgetBornType;
(function (GadgetBornType) {
    /**
     * @generated from protobuf enum value: GADGET_BORN_NONE = 0;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_NONE"] = 0] = "GADGET_BORN_NONE";
    /**
     * @generated from protobuf enum value: GADGET_BORN_IN_AIR = 1;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_IN_AIR"] = 1] = "GADGET_BORN_IN_AIR";
    /**
     * @generated from protobuf enum value: GADGET_BORN_PLAYER = 2;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_PLAYER"] = 2] = "GADGET_BORN_PLAYER";
    /**
     * @generated from protobuf enum value: GADGET_BORN_MONSTER_HIT = 3;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_MONSTER_HIT"] = 3] = "GADGET_BORN_MONSTER_HIT";
    /**
     * @generated from protobuf enum value: GADGET_BORN_MONSTER_DIE = 4;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_MONSTER_DIE"] = 4] = "GADGET_BORN_MONSTER_DIE";
    /**
     * @generated from protobuf enum value: GADGET_BORN_GADGET = 5;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_GADGET"] = 5] = "GADGET_BORN_GADGET";
    /**
     * @generated from protobuf enum value: GADGET_BORN_GROUND = 6;
     */
    GadgetBornType[GadgetBornType["GADGET_BORN_GROUND"] = 6] = "GADGET_BORN_GROUND";
})(GadgetBornType || (GadgetBornType = {}));
