// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "GadgetBornType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum GadgetBornType
 */
export enum GadgetBornType {
    /**
     * @generated from protobuf enum value: GADGET_BORN_NONE = 0;
     */
    GADGET_BORN_NONE = 0,
    /**
     * @generated from protobuf enum value: GADGET_BORN_IN_AIR = 1;
     */
    GADGET_BORN_IN_AIR = 1,
    /**
     * @generated from protobuf enum value: GADGET_BORN_PLAYER = 2;
     */
    GADGET_BORN_PLAYER = 2,
    /**
     * @generated from protobuf enum value: GADGET_BORN_MONSTER_HIT = 3;
     */
    GADGET_BORN_MONSTER_HIT = 3,
    /**
     * @generated from protobuf enum value: GADGET_BORN_MONSTER_DIE = 4;
     */
    GADGET_BORN_MONSTER_DIE = 4,
    /**
     * @generated from protobuf enum value: GADGET_BORN_GADGET = 5;
     */
    GADGET_BORN_GADGET = 5,
    /**
     * @generated from protobuf enum value: GADGET_BORN_GROUND = 6;
     */
    GADGET_BORN_GROUND = 6
}
