// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "GetPlayerSocialDetailRsp.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SocialDetail } from "./SocialDetail";
/**
 * @generated from protobuf message GetPlayerSocialDetailRsp
 */
export interface GetPlayerSocialDetailRsp {
    /**
     * @generated from protobuf field: int32 retcode = 1;
     */
    retcode: number;
    /**
     * @generated from protobuf field: SocialDetail detail_data = 2;
     */
    detailData?: SocialDetail;
}
/**
 * @generated from protobuf enum GetPlayerSocialDetailRsp.CmdId
 */
export declare enum GetPlayerSocialDetailRsp_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 4079;
     */
    CMD_ID = 4079
}
declare class GetPlayerSocialDetailRsp$Type extends MessageType<GetPlayerSocialDetailRsp> {
    constructor();
    create(value?: PartialMessage<GetPlayerSocialDetailRsp>): GetPlayerSocialDetailRsp;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPlayerSocialDetailRsp): GetPlayerSocialDetailRsp;
    internalBinaryWrite(message: GetPlayerSocialDetailRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message GetPlayerSocialDetailRsp
 */
export declare const GetPlayerSocialDetailRsp: GetPlayerSocialDetailRsp$Type;
export {};
