// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "MassivePropSyncInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MassivePropParam } from "./MassivePropParam";
/**
 * @generated from protobuf message MassivePropSyncInfo
 */
export interface MassivePropSyncInfo {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: repeated MassivePropParam prop_list = 2;
     */
    propList: MassivePropParam[];
}
declare class MassivePropSyncInfo$Type extends MessageType<MassivePropSyncInfo> {
    constructor();
    create(value?: PartialMessage<MassivePropSyncInfo>): MassivePropSyncInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MassivePropSyncInfo): MassivePropSyncInfo;
    internalBinaryWrite(message: MassivePropSyncInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MassivePropSyncInfo
 */
export declare const MassivePropSyncInfo: MassivePropSyncInfo$Type;
export {};
