// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "MaterialDeleteInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message MaterialDeleteInfo
 */
export interface MaterialDeleteInfo {
    /**
     * @generated from protobuf oneof: DeleteInfo
     */
    deleteInfo: {
        oneofKind: "countDownDelete";
        /**
         * @generated from protobuf field: MaterialDeleteInfo.CountDownDelete count_down_delete = 2;
         */
        countDownDelete: MaterialDeleteInfo_CountDownDelete;
    } | {
        oneofKind: "dateDelete";
        /**
         * @generated from protobuf field: MaterialDeleteInfo.DateTimeDelete date_delete = 3;
         */
        dateDelete: MaterialDeleteInfo_DateTimeDelete;
    } | {
        oneofKind: "delayWeekCountDownDelete";
        /**
         * @generated from protobuf field: MaterialDeleteInfo.DelayWeekCountDownDelete delay_week_count_down_delete = 4;
         */
        delayWeekCountDownDelete: MaterialDeleteInfo_DelayWeekCountDownDelete;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: bool has_delete_config = 1;
     */
    hasDeleteConfig: boolean;
}
/**
 * @generated from protobuf message MaterialDeleteInfo.CountDownDelete
 */
export interface MaterialDeleteInfo_CountDownDelete {
    /**
     * @generated from protobuf field: map<uint32, uint32> delete_time_num_map = 1;
     */
    deleteTimeNumMap: {
        [key: number]: number;
    };
    /**
     * @generated from protobuf field: uint32 config_count_down_time = 2;
     */
    configCountDownTime: number;
}
/**
 * @generated from protobuf message MaterialDeleteInfo.DateTimeDelete
 */
export interface MaterialDeleteInfo_DateTimeDelete {
    /**
     * @generated from protobuf field: uint32 delete_time = 1;
     */
    deleteTime: number;
}
/**
 * @generated from protobuf message MaterialDeleteInfo.DelayWeekCountDownDelete
 */
export interface MaterialDeleteInfo_DelayWeekCountDownDelete {
    /**
     * @generated from protobuf field: map<uint32, uint32> delete_time_num_map = 1;
     */
    deleteTimeNumMap: {
        [key: number]: number;
    };
    /**
     * @generated from protobuf field: uint32 config_delay_week = 2;
     */
    configDelayWeek: number;
    /**
     * @generated from protobuf field: uint32 config_count_down_time = 3;
     */
    configCountDownTime: number;
}
declare class MaterialDeleteInfo$Type extends MessageType<MaterialDeleteInfo> {
    constructor();
    create(value?: PartialMessage<MaterialDeleteInfo>): MaterialDeleteInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialDeleteInfo): MaterialDeleteInfo;
    internalBinaryWrite(message: MaterialDeleteInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MaterialDeleteInfo
 */
export declare const MaterialDeleteInfo: MaterialDeleteInfo$Type;
declare class MaterialDeleteInfo_CountDownDelete$Type extends MessageType<MaterialDeleteInfo_CountDownDelete> {
    constructor();
    create(value?: PartialMessage<MaterialDeleteInfo_CountDownDelete>): MaterialDeleteInfo_CountDownDelete;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialDeleteInfo_CountDownDelete): MaterialDeleteInfo_CountDownDelete;
    private binaryReadMap1;
    internalBinaryWrite(message: MaterialDeleteInfo_CountDownDelete, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MaterialDeleteInfo.CountDownDelete
 */
export declare const MaterialDeleteInfo_CountDownDelete: MaterialDeleteInfo_CountDownDelete$Type;
declare class MaterialDeleteInfo_DateTimeDelete$Type extends MessageType<MaterialDeleteInfo_DateTimeDelete> {
    constructor();
    create(value?: PartialMessage<MaterialDeleteInfo_DateTimeDelete>): MaterialDeleteInfo_DateTimeDelete;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialDeleteInfo_DateTimeDelete): MaterialDeleteInfo_DateTimeDelete;
    internalBinaryWrite(message: MaterialDeleteInfo_DateTimeDelete, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MaterialDeleteInfo.DateTimeDelete
 */
export declare const MaterialDeleteInfo_DateTimeDelete: MaterialDeleteInfo_DateTimeDelete$Type;
declare class MaterialDeleteInfo_DelayWeekCountDownDelete$Type extends MessageType<MaterialDeleteInfo_DelayWeekCountDownDelete> {
    constructor();
    create(value?: PartialMessage<MaterialDeleteInfo_DelayWeekCountDownDelete>): MaterialDeleteInfo_DelayWeekCountDownDelete;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialDeleteInfo_DelayWeekCountDownDelete): MaterialDeleteInfo_DelayWeekCountDownDelete;
    private binaryReadMap1;
    internalBinaryWrite(message: MaterialDeleteInfo_DelayWeekCountDownDelete, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MaterialDeleteInfo.DelayWeekCountDownDelete
 */
export declare const MaterialDeleteInfo_DelayWeekCountDownDelete: MaterialDeleteInfo_DelayWeekCountDownDelete$Type;
export {};
