// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "MotionState.proto" (syntax proto3),// tslint:disable
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "MotionState.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum MotionState
 */
export var MotionState;
(function (MotionState) {
    /**
     * @generated from protobuf enum value: MOTION_NONE = 0;
     */
    MotionState[MotionState["MOTION_NONE"] = 0] = "MOTION_NONE";
    /**
     * @generated from protobuf enum value: MOTION_RESET = 1;
     */
    MotionState[MotionState["MOTION_RESET"] = 1] = "MOTION_RESET";
    /**
     * @generated from protobuf enum value: MOTION_STANDBY = 2;
     */
    MotionState[MotionState["MOTION_STANDBY"] = 2] = "MOTION_STANDBY";
    /**
     * @generated from protobuf enum value: MOTION_STANDBY_MOVE = 3;
     */
    MotionState[MotionState["MOTION_STANDBY_MOVE"] = 3] = "MOTION_STANDBY_MOVE";
    /**
     * @generated from protobuf enum value: MOTION_WALK = 4;
     */
    MotionState[MotionState["MOTION_WALK"] = 4] = "MOTION_WALK";
    /**
     * @generated from protobuf enum value: MOTION_RUN = 5;
     */
    MotionState[MotionState["MOTION_RUN"] = 5] = "MOTION_RUN";
    /**
     * @generated from protobuf enum value: MOTION_DASH = 6;
     */
    MotionState[MotionState["MOTION_DASH"] = 6] = "MOTION_DASH";
    /**
     * @generated from protobuf enum value: MOTION_CLIMB = 7;
     */
    MotionState[MotionState["MOTION_CLIMB"] = 7] = "MOTION_CLIMB";
    /**
     * @generated from protobuf enum value: MOTION_CLIMB_JUMP = 8;
     */
    MotionState[MotionState["MOTION_CLIMB_JUMP"] = 8] = "MOTION_CLIMB_JUMP";
    /**
     * @generated from protobuf enum value: MOTION_STANDBY_TO_CLIMB = 9;
     */
    MotionState[MotionState["MOTION_STANDBY_TO_CLIMB"] = 9] = "MOTION_STANDBY_TO_CLIMB";
    /**
     * @generated from protobuf enum value: MOTION_FIGHT = 10;
     */
    MotionState[MotionState["MOTION_FIGHT"] = 10] = "MOTION_FIGHT";
    /**
     * @generated from protobuf enum value: MOTION_JUMP = 11;
     */
    MotionState[MotionState["MOTION_JUMP"] = 11] = "MOTION_JUMP";
    /**
     * @generated from protobuf enum value: MOTION_DROP = 12;
     */
    MotionState[MotionState["MOTION_DROP"] = 12] = "MOTION_DROP";
    /**
     * @generated from protobuf enum value: MOTION_FLY = 13;
     */
    MotionState[MotionState["MOTION_FLY"] = 13] = "MOTION_FLY";
    /**
     * @generated from protobuf enum value: MOTION_SWIM_MOVE = 14;
     */
    MotionState[MotionState["MOTION_SWIM_MOVE"] = 14] = "MOTION_SWIM_MOVE";
    /**
     * @generated from protobuf enum value: MOTION_SWIM_IDLE = 15;
     */
    MotionState[MotionState["MOTION_SWIM_IDLE"] = 15] = "MOTION_SWIM_IDLE";
    /**
     * @generated from protobuf enum value: MOTION_SWIM_DASH = 16;
     */
    MotionState[MotionState["MOTION_SWIM_DASH"] = 16] = "MOTION_SWIM_DASH";
    /**
     * @generated from protobuf enum value: MOTION_SWIM_JUMP = 17;
     */
    MotionState[MotionState["MOTION_SWIM_JUMP"] = 17] = "MOTION_SWIM_JUMP";
    /**
     * @generated from protobuf enum value: MOTION_SLIP = 18;
     */
    MotionState[MotionState["MOTION_SLIP"] = 18] = "MOTION_SLIP";
    /**
     * @generated from protobuf enum value: MOTION_GO_UPSTAIRS = 19;
     */
    MotionState[MotionState["MOTION_GO_UPSTAIRS"] = 19] = "MOTION_GO_UPSTAIRS";
    /**
     * @generated from protobuf enum value: MOTION_FALL_ON_GROUND = 20;
     */
    MotionState[MotionState["MOTION_FALL_ON_GROUND"] = 20] = "MOTION_FALL_ON_GROUND";
    /**
     * @generated from protobuf enum value: MOTION_JUMP_UP_WALL_FOR_STANDBY = 21;
     */
    MotionState[MotionState["MOTION_JUMP_UP_WALL_FOR_STANDBY"] = 21] = "MOTION_JUMP_UP_WALL_FOR_STANDBY";
    /**
     * @generated from protobuf enum value: MOTION_JUMP_OFF_WALL = 22;
     */
    MotionState[MotionState["MOTION_JUMP_OFF_WALL"] = 22] = "MOTION_JUMP_OFF_WALL";
    /**
     * @generated from protobuf enum value: MOTION_POWERED_FLY = 23;
     */
    MotionState[MotionState["MOTION_POWERED_FLY"] = 23] = "MOTION_POWERED_FLY";
    /**
     * @generated from protobuf enum value: MOTION_LADDER_IDLE = 24;
     */
    MotionState[MotionState["MOTION_LADDER_IDLE"] = 24] = "MOTION_LADDER_IDLE";
    /**
     * @generated from protobuf enum value: MOTION_LADDER_MOVE = 25;
     */
    MotionState[MotionState["MOTION_LADDER_MOVE"] = 25] = "MOTION_LADDER_MOVE";
    /**
     * @generated from protobuf enum value: MOTION_LADDER_SLIP = 26;
     */
    MotionState[MotionState["MOTION_LADDER_SLIP"] = 26] = "MOTION_LADDER_SLIP";
    /**
     * @generated from protobuf enum value: MOTION_STANDBY_TO_LADDER = 27;
     */
    MotionState[MotionState["MOTION_STANDBY_TO_LADDER"] = 27] = "MOTION_STANDBY_TO_LADDER";
    /**
     * @generated from protobuf enum value: MOTION_LADDER_TO_STANDBY = 28;
     */
    MotionState[MotionState["MOTION_LADDER_TO_STANDBY"] = 28] = "MOTION_LADDER_TO_STANDBY";
    /**
     * @generated from protobuf enum value: MOTION_DANGER_STANDBY = 29;
     */
    MotionState[MotionState["MOTION_DANGER_STANDBY"] = 29] = "MOTION_DANGER_STANDBY";
    /**
     * @generated from protobuf enum value: MOTION_DANGER_STANDBY_MOVE = 30;
     */
    MotionState[MotionState["MOTION_DANGER_STANDBY_MOVE"] = 30] = "MOTION_DANGER_STANDBY_MOVE";
    /**
     * @generated from protobuf enum value: MOTION_DANGER_WALK = 31;
     */
    MotionState[MotionState["MOTION_DANGER_WALK"] = 31] = "MOTION_DANGER_WALK";
    /**
     * @generated from protobuf enum value: MOTION_DANGER_RUN = 32;
     */
    MotionState[MotionState["MOTION_DANGER_RUN"] = 32] = "MOTION_DANGER_RUN";
    /**
     * @generated from protobuf enum value: MOTION_DANGER_DASH = 33;
     */
    MotionState[MotionState["MOTION_DANGER_DASH"] = 33] = "MOTION_DANGER_DASH";
    /**
     * @generated from protobuf enum value: MOTION_CROUCH_IDLE = 34;
     */
    MotionState[MotionState["MOTION_CROUCH_IDLE"] = 34] = "MOTION_CROUCH_IDLE";
    /**
     * @generated from protobuf enum value: MOTION_CROUCH_MOVE = 35;
     */
    MotionState[MotionState["MOTION_CROUCH_MOVE"] = 35] = "MOTION_CROUCH_MOVE";
    /**
     * @generated from protobuf enum value: MOTION_CROUCH_ROLL = 36;
     */
    MotionState[MotionState["MOTION_CROUCH_ROLL"] = 36] = "MOTION_CROUCH_ROLL";
    /**
     * @generated from protobuf enum value: MOTION_NOTIFY = 37;
     */
    MotionState[MotionState["MOTION_NOTIFY"] = 37] = "MOTION_NOTIFY";
    /**
     * @generated from protobuf enum value: MOTION_LAND_SPEED = 38;
     */
    MotionState[MotionState["MOTION_LAND_SPEED"] = 38] = "MOTION_LAND_SPEED";
    /**
     * @generated from protobuf enum value: MOTION_MOVE_FAIL_ACK = 39;
     */
    MotionState[MotionState["MOTION_MOVE_FAIL_ACK"] = 39] = "MOTION_MOVE_FAIL_ACK";
    /**
     * @generated from protobuf enum value: MOTION_WATERFALL = 40;
     */
    MotionState[MotionState["MOTION_WATERFALL"] = 40] = "MOTION_WATERFALL";
    /**
     * @generated from protobuf enum value: MOTION_DASH_BEFORE_SHAKE = 41;
     */
    MotionState[MotionState["MOTION_DASH_BEFORE_SHAKE"] = 41] = "MOTION_DASH_BEFORE_SHAKE";
    /**
     * @generated from protobuf enum value: MOTION_SIT_IDLE = 42;
     */
    MotionState[MotionState["MOTION_SIT_IDLE"] = 42] = "MOTION_SIT_IDLE";
    /**
     * @generated from protobuf enum value: MOTION_FORCE_SET_POS = 43;
     */
    MotionState[MotionState["MOTION_FORCE_SET_POS"] = 43] = "MOTION_FORCE_SET_POS";
    /**
     * @generated from protobuf enum value: MOTION_QUEST_FORCE_DRAG = 44;
     */
    MotionState[MotionState["MOTION_QUEST_FORCE_DRAG"] = 44] = "MOTION_QUEST_FORCE_DRAG";
    /**
     * @generated from protobuf enum value: MOTION_FOLLOW_ROUTE = 45;
     */
    MotionState[MotionState["MOTION_FOLLOW_ROUTE"] = 45] = "MOTION_FOLLOW_ROUTE";
    /**
     * @generated from protobuf enum value: MOTION_SKIFF_BOARDING = 46;
     */
    MotionState[MotionState["MOTION_SKIFF_BOARDING"] = 46] = "MOTION_SKIFF_BOARDING";
    /**
     * @generated from protobuf enum value: MOTION_SKIFF_NORMAL = 47;
     */
    MotionState[MotionState["MOTION_SKIFF_NORMAL"] = 47] = "MOTION_SKIFF_NORMAL";
    /**
     * @generated from protobuf enum value: MOTION_SKIFF_DASH = 48;
     */
    MotionState[MotionState["MOTION_SKIFF_DASH"] = 48] = "MOTION_SKIFF_DASH";
    /**
     * @generated from protobuf enum value: MOTION_SKIFF_POWERED_DASH = 49;
     */
    MotionState[MotionState["MOTION_SKIFF_POWERED_DASH"] = 49] = "MOTION_SKIFF_POWERED_DASH";
    /**
     * @generated from protobuf enum value: MOTION_DESTROY_VEHICLE = 50;
     */
    MotionState[MotionState["MOTION_DESTROY_VEHICLE"] = 50] = "MOTION_DESTROY_VEHICLE";
    /**
     * @generated from protobuf enum value: MOTION_FLY_IDLE = 51;
     */
    MotionState[MotionState["MOTION_FLY_IDLE"] = 51] = "MOTION_FLY_IDLE";
    /**
     * @generated from protobuf enum value: MOTION_FLY_SLOW = 52;
     */
    MotionState[MotionState["MOTION_FLY_SLOW"] = 52] = "MOTION_FLY_SLOW";
    /**
     * @generated from protobuf enum value: MOTION_FLY_FAST = 53;
     */
    MotionState[MotionState["MOTION_FLY_FAST"] = 53] = "MOTION_FLY_FAST";
    /**
     * @generated from protobuf enum value: MOTION_NUM = 54;
     */
    MotionState[MotionState["MOTION_NUM"] = 54] = "MOTION_NUM";
})(MotionState || (MotionState = {}));
