// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "MPLevelEntityInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AbilitySyncStateInfo } from "./AbilitySyncStateInfo";
/**
 * @generated from protobuf message MPLevelEntityInfo
 */
export interface MPLevelEntityInfo {
    /**
     * @generated from protobuf field: uint32 entity_id = 1;
     */
    entityId: number;
    /**
     * @generated from protobuf field: uint32 authority_peer_id = 2;
     */
    authorityPeerId: number;
    /**
     * @generated from protobuf field: AbilitySyncStateInfo ability_info = 3;
     */
    abilityInfo?: AbilitySyncStateInfo;
}
declare class MPLevelEntityInfo$Type extends MessageType<MPLevelEntityInfo> {
    constructor();
    create(value?: PartialMessage<MPLevelEntityInfo>): MPLevelEntityInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MPLevelEntityInfo): MPLevelEntityInfo;
    internalBinaryWrite(message: MPLevelEntityInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message MPLevelEntityInfo
 */
export declare const MPLevelEntityInfo: MPLevelEntityInfo$Type;
export {};
