// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "MpSettingType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum MpSettingType
 */
export enum MpSettingType {
    /**
     * @generated from protobuf enum value: MP_SETTING_NO_ENTER = 0;
     */
    MP_SETTING_NO_ENTER = 0,
    /**
     * @generated from protobuf enum value: MP_SETTING_ENTER_FREELY = 1;
     */
    MP_SETTING_ENTER_FREELY = 1,
    /**
     * @generated from protobuf enum value: MP_SETTING_ENTER_AFTER_APPLY = 2;
     */
    MP_SETTING_ENTER_AFTER_APPLY = 2
}
