// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "OnlinePlayerInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ProfilePicture } from "./ProfilePicture";
import { MpSettingType } from "./MpSettingType";
/**
 * @generated from protobuf message OnlinePlayerInfo
 */
export interface OnlinePlayerInfo {
    /**
     * @generated from protobuf field: uint32 uid = 1;
     */
    uid: number;
    /**
     * @generated from protobuf field: string nickname = 2;
     */
    nickname: string;
    /**
     * @generated from protobuf field: uint32 player_level = 3;
     */
    playerLevel: number;
    /**
     * @generated from protobuf field: uint32 avatar_id = 4;
     */
    avatarId: number;
    /**
     * @generated from protobuf field: MpSettingType mp_setting_type = 5;
     */
    mpSettingType: MpSettingType;
    /**
     * @generated from protobuf field: uint32 cur_player_num_in_world = 6;
     */
    curPlayerNumInWorld: number;
    /**
     * @generated from protobuf field: uint32 world_level = 7;
     */
    worldLevel: number;
    /**
     * @generated from protobuf field: string online_id = 8;
     */
    onlineId: string;
    /**
     * @generated from protobuf field: uint32 name_card_id = 9;
     */
    nameCardId: number;
    /**
     * @generated from protobuf field: repeated uint32 blacklist_uid_list = 10;
     */
    blacklistUidList: number[];
    /**
     * @generated from protobuf field: string signature = 11;
     */
    signature: string;
    /**
     * @generated from protobuf field: ProfilePicture profile_picture = 12;
     */
    profilePicture?: ProfilePicture;
    /**
     * @generated from protobuf field: string psn_id = 13;
     */
    psnId: string;
}
declare class OnlinePlayerInfo$Type extends MessageType<OnlinePlayerInfo> {
    constructor();
    create(value?: PartialMessage<OnlinePlayerInfo>): OnlinePlayerInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnlinePlayerInfo): OnlinePlayerInfo;
    internalBinaryWrite(message: OnlinePlayerInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message OnlinePlayerInfo
 */
export declare const OnlinePlayerInfo: OnlinePlayerInfo$Type;
export {};
