// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "PlatformType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum PlatformType
 */
export enum PlatformType {
    /**
     * @generated from protobuf enum value: EDITOR = 0;
     */
    EDITOR = 0,
    /**
     * @generated from protobuf enum value: IOS = 1;
     */
    IOS = 1,
    /**
     * @generated from protobuf enum value: ANDROID = 2;
     */
    ANDROID = 2,
    /**
     * @generated from protobuf enum value: PC = 3;
     */
    PC = 3,
    /**
     * @generated from protobuf enum value: PS4 = 4;
     */
    PS4 = 4,
    /**
     * @generated from protobuf enum value: SERVER = 5;
     */
    SERVER = 5,
    /**
     * @generated from protobuf enum value: CLOUD_ANDROID = 6;
     */
    CLOUD_ANDROID = 6,
    /**
     * @generated from protobuf enum value: CLOUD_IOS = 7;
     */
    CLOUD_IOS = 7,
    /**
     * @generated from protobuf enum value: PS5 = 8;
     */
    PS5 = 8,
    /**
     * @generated from protobuf enum value: CLOUD_WEB = 9;
     */
    CLOUD_WEB = 9,
    /**
     * @generated from protobuf enum value: CLOUD_TV = 10;
     */
    CLOUD_TV = 10
}
