// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "PlayerEnterSceneInfoNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MPLevelEntityInfo } from "./MPLevelEntityInfo";
import { TeamEnterSceneInfo } from "./TeamEnterSceneInfo";
import { AvatarEnterSceneInfo } from "./AvatarEnterSceneInfo";
/**
 * @generated from protobuf message PlayerEnterSceneInfoNotify
 */
export interface PlayerEnterSceneInfoNotify {
    /**
     * @generated from protobuf field: uint32 cur_avatar_entity_id = 1;
     */
    curAvatarEntityId: number;
    /**
     * @generated from protobuf field: repeated AvatarEnterSceneInfo avatar_enter_info = 2;
     */
    avatarEnterInfo: AvatarEnterSceneInfo[];
    /**
     * @generated from protobuf field: TeamEnterSceneInfo team_enter_info = 3;
     */
    teamEnterInfo?: TeamEnterSceneInfo;
    /**
     * @generated from protobuf field: MPLevelEntityInfo mp_level_entity_info = 4;
     */
    mpLevelEntityInfo?: MPLevelEntityInfo;
    /**
     * @generated from protobuf field: uint32 enter_scene_token = 5;
     */
    enterSceneToken: number;
}
/**
 * @generated from protobuf enum PlayerEnterSceneInfoNotify.CmdId
 */
export enum PlayerEnterSceneInfoNotify_CmdId {
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    IS_ALLOW_CLIENT = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 246;
     */
    CMD_ID = 246
}
// @generated message type with reflection information, may provide speed optimized methods
class PlayerEnterSceneInfoNotify$Type extends MessageType<PlayerEnterSceneInfoNotify> {
    constructor() {
        super("PlayerEnterSceneInfoNotify", [
            { no: 1, name: "cur_avatar_entity_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "avatar_enter_info", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AvatarEnterSceneInfo },
            { no: 3, name: "team_enter_info", kind: "message", T: () => TeamEnterSceneInfo },
            { no: 4, name: "mp_level_entity_info", kind: "message", T: () => MPLevelEntityInfo },
            { no: 5, name: "enter_scene_token", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<PlayerEnterSceneInfoNotify>): PlayerEnterSceneInfoNotify {
        const message = { curAvatarEntityId: 0, avatarEnterInfo: [], enterSceneToken: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PlayerEnterSceneInfoNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayerEnterSceneInfoNotify): PlayerEnterSceneInfoNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 cur_avatar_entity_id */ 1:
                    message.curAvatarEntityId = reader.uint32();
                    break;
                case /* repeated AvatarEnterSceneInfo avatar_enter_info */ 2:
                    message.avatarEnterInfo.push(AvatarEnterSceneInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* TeamEnterSceneInfo team_enter_info */ 3:
                    message.teamEnterInfo = TeamEnterSceneInfo.internalBinaryRead(reader, reader.uint32(), options, message.teamEnterInfo);
                    break;
                case /* MPLevelEntityInfo mp_level_entity_info */ 4:
                    message.mpLevelEntityInfo = MPLevelEntityInfo.internalBinaryRead(reader, reader.uint32(), options, message.mpLevelEntityInfo);
                    break;
                case /* uint32 enter_scene_token */ 5:
                    message.enterSceneToken = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlayerEnterSceneInfoNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 cur_avatar_entity_id = 1; */
        if (message.curAvatarEntityId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.curAvatarEntityId);
        /* repeated AvatarEnterSceneInfo avatar_enter_info = 2; */
        for (let i = 0; i < message.avatarEnterInfo.length; i++)
            AvatarEnterSceneInfo.internalBinaryWrite(message.avatarEnterInfo[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* TeamEnterSceneInfo team_enter_info = 3; */
        if (message.teamEnterInfo)
            TeamEnterSceneInfo.internalBinaryWrite(message.teamEnterInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* MPLevelEntityInfo mp_level_entity_info = 4; */
        if (message.mpLevelEntityInfo)
            MPLevelEntityInfo.internalBinaryWrite(message.mpLevelEntityInfo, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* uint32 enter_scene_token = 5; */
        if (message.enterSceneToken !== 0)
            writer.tag(5, WireType.Varint).uint32(message.enterSceneToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PlayerEnterSceneInfoNotify
 */
export const PlayerEnterSceneInfoNotify = new PlayerEnterSceneInfoNotify$Type();
