// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "PlayerGameTimeNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message PlayerGameTimeNotify
 */
export interface PlayerGameTimeNotify {
    /**
     * @generated from protobuf field: uint32 game_time = 1;
     */
    gameTime: number;
    /**
     * @generated from protobuf field: uint32 uid = 2;
     */
    uid: number;
    /**
     * @generated from protobuf field: bool is_home = 3;
     */
    isHome: boolean;
}
/**
 * @generated from protobuf enum PlayerGameTimeNotify.CmdId
 */
export declare enum PlayerGameTimeNotify_CmdId {
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    IS_ALLOW_CLIENT = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 112;
     */
    CMD_ID = 112
}
declare class PlayerGameTimeNotify$Type extends MessageType<PlayerGameTimeNotify> {
    constructor();
    create(value?: PartialMessage<PlayerGameTimeNotify>): PlayerGameTimeNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayerGameTimeNotify): PlayerGameTimeNotify;
    internalBinaryWrite(message: PlayerGameTimeNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message PlayerGameTimeNotify
 */
export declare const PlayerGameTimeNotify: PlayerGameTimeNotify$Type;
export {};
