"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProtEntityType = void 0;
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "ProtEntityType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum ProtEntityType
 */
var ProtEntityType;
(function (ProtEntityType) {
    /**
     * @generated from protobuf enum value: PROT_ENTITY_NONE = 0;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_NONE"] = 0] = "PROT_ENTITY_NONE";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_AVATAR = 1;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_AVATAR"] = 1] = "PROT_ENTITY_AVATAR";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MONSTER = 2;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_MONSTER"] = 2] = "PROT_ENTITY_MONSTER";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_NPC = 3;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_NPC"] = 3] = "PROT_ENTITY_NPC";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_GADGET = 4;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_GADGET"] = 4] = "PROT_ENTITY_GADGET";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_REGION = 5;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_REGION"] = 5] = "PROT_ENTITY_REGION";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_WEAPON = 6;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_WEAPON"] = 6] = "PROT_ENTITY_WEAPON";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_WEATHER = 7;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_WEATHER"] = 7] = "PROT_ENTITY_WEATHER";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_SCENE = 8;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_SCENE"] = 8] = "PROT_ENTITY_SCENE";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_TEAM = 9;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_TEAM"] = 9] = "PROT_ENTITY_TEAM";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MASSIVE_ENTITY = 10;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_MASSIVE_ENTITY"] = 10] = "PROT_ENTITY_MASSIVE_ENTITY";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MP_LEVEL = 11;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_MP_LEVEL"] = 11] = "PROT_ENTITY_MP_LEVEL";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_PLAY_TEAM_ENTITY = 12;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_PLAY_TEAM_ENTITY"] = 12] = "PROT_ENTITY_PLAY_TEAM_ENTITY";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_EYE_POINT = 13;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_EYE_POINT"] = 13] = "PROT_ENTITY_EYE_POINT";
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MAX = 14;
     */
    ProtEntityType[ProtEntityType["PROT_ENTITY_MAX"] = 14] = "PROT_ENTITY_MAX";
})(ProtEntityType = exports.ProtEntityType || (exports.ProtEntityType = {}));
