// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "ProtEntityType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum ProtEntityType
 */
export declare enum ProtEntityType {
    /**
     * @generated from protobuf enum value: PROT_ENTITY_NONE = 0;
     */
    PROT_ENTITY_NONE = 0,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_AVATAR = 1;
     */
    PROT_ENTITY_AVATAR = 1,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MONSTER = 2;
     */
    PROT_ENTITY_MONSTER = 2,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_NPC = 3;
     */
    PROT_ENTITY_NPC = 3,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_GADGET = 4;
     */
    PROT_ENTITY_GADGET = 4,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_REGION = 5;
     */
    PROT_ENTITY_REGION = 5,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_WEAPON = 6;
     */
    PROT_ENTITY_WEAPON = 6,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_WEATHER = 7;
     */
    PROT_ENTITY_WEATHER = 7,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_SCENE = 8;
     */
    PROT_ENTITY_SCENE = 8,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_TEAM = 9;
     */
    PROT_ENTITY_TEAM = 9,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MASSIVE_ENTITY = 10;
     */
    PROT_ENTITY_MASSIVE_ENTITY = 10,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MP_LEVEL = 11;
     */
    PROT_ENTITY_MP_LEVEL = 11,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_PLAY_TEAM_ENTITY = 12;
     */
    PROT_ENTITY_PLAY_TEAM_ENTITY = 12,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_EYE_POINT = 13;
     */
    PROT_ENTITY_EYE_POINT = 13,
    /**
     * @generated from protobuf enum value: PROT_ENTITY_MAX = 14;
     */
    PROT_ENTITY_MAX = 14
}
