// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "QueryCurrRegionHttpRsp.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { RegionInfo } from "./RegionInfo";
import { StopServerInfo } from "./StopServerInfo";
import { ForceUpdateInfo } from "./ForceUpdateInfo";
/**
 * @generated from protobuf message QueryCurrRegionHttpRsp
 */
export interface QueryCurrRegionHttpRsp {
    /**
     * @generated from protobuf oneof: Detail
     */
    detail: {
        oneofKind: "forceUdpate";
        /**
         * @generated from protobuf field: ForceUpdateInfo force_udpate = 4;
         */
        forceUdpate: ForceUpdateInfo;
    } | {
        oneofKind: "stopServer";
        /**
         * @generated from protobuf field: StopServerInfo stop_server = 5;
         */
        stopServer: StopServerInfo;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: int32 retcode = 1;
     */
    retcode: number;
    /**
     * @generated from protobuf field: string msg = 2;
     */
    msg: string;
    /**
     * @generated from protobuf field: RegionInfo region_info = 3;
     */
    regionInfo?: RegionInfo;
    /**
     * @generated from protobuf field: bytes client_secret_key = 11;
     */
    clientSecretKey: Uint8Array;
    /**
     * @generated from protobuf field: bytes region_custom_config_encrypted = 12;
     */
    regionCustomConfigEncrypted: Uint8Array;
    /**
     * @generated from protobuf field: bytes client_region_custom_config_encrypted = 13;
     */
    clientRegionCustomConfigEncrypted: Uint8Array;
}
declare class QueryCurrRegionHttpRsp$Type extends MessageType<QueryCurrRegionHttpRsp> {
    constructor();
    create(value?: PartialMessage<QueryCurrRegionHttpRsp>): QueryCurrRegionHttpRsp;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryCurrRegionHttpRsp): QueryCurrRegionHttpRsp;
    internalBinaryWrite(message: QueryCurrRegionHttpRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message QueryCurrRegionHttpRsp
 */
export declare const QueryCurrRegionHttpRsp: QueryCurrRegionHttpRsp$Type;
export {};
