// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "Route.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { RoutePoint } from "./RoutePoint";
/**
 * @generated from protobuf message Route
 */
export interface Route {
    /**
     * @generated from protobuf field: repeated RoutePoint route_points = 1;
     */
    routePoints: RoutePoint[];
    /**
     * @generated from protobuf field: uint32 route_type = 2;
     */
    routeType: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Route$Type extends MessageType<Route> {
    constructor() {
        super("Route", [
            { no: 1, name: "route_points", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => RoutePoint },
            { no: 2, name: "route_type", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<Route>): Route {
        const message = { routePoints: [], routeType: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Route>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Route): Route {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated RoutePoint route_points */ 1:
                    message.routePoints.push(RoutePoint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint32 route_type */ 2:
                    message.routeType = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Route, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated RoutePoint route_points = 1; */
        for (let i = 0; i < message.routePoints.length; i++)
            RoutePoint.internalBinaryWrite(message.routePoints[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* uint32 route_type = 2; */
        if (message.routeType !== 0)
            writer.tag(2, WireType.Varint).uint32(message.routeType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Route
 */
export const Route = new Route$Type();
