// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "SceneTeamUpdateNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SceneTeamAvatar } from "./SceneTeamAvatar";
/**
 * @generated from protobuf message SceneTeamUpdateNotify
 */
export interface SceneTeamUpdateNotify {
    /**
     * @generated from protobuf field: repeated SceneTeamAvatar scene_team_avatar_list = 1;
     */
    sceneTeamAvatarList: SceneTeamAvatar[];
    /**
     * @generated from protobuf field: bool is_in_mp = 3;
     */
    isInMp: boolean;
}
/**
 * @generated from protobuf enum SceneTeamUpdateNotify.CmdId
 */
export declare enum SceneTeamUpdateNotify_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 1793;
     */
    CMD_ID = 1793
}
declare class SceneTeamUpdateNotify$Type extends MessageType<SceneTeamUpdateNotify> {
    constructor();
    create(value?: PartialMessage<SceneTeamUpdateNotify>): SceneTeamUpdateNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneTeamUpdateNotify): SceneTeamUpdateNotify;
    internalBinaryWrite(message: SceneTeamUpdateNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message SceneTeamUpdateNotify
 */
export declare const SceneTeamUpdateNotify: SceneTeamUpdateNotify$Type;
export {};
