// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "SceneTeamUpdateNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SceneTeamAvatar } from "./SceneTeamAvatar";
/**
 * @generated from protobuf message SceneTeamUpdateNotify
 */
export interface SceneTeamUpdateNotify {
    /**
     * @generated from protobuf field: repeated SceneTeamAvatar scene_team_avatar_list = 1;
     */
    sceneTeamAvatarList: SceneTeamAvatar[];
    /**
     * @generated from protobuf field: bool is_in_mp = 3;
     */
    isInMp: boolean;
}
/**
 * @generated from protobuf enum SceneTeamUpdateNotify.CmdId
 */
export enum SceneTeamUpdateNotify_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 1793;
     */
    CMD_ID = 1793
}
// @generated message type with reflection information, may provide speed optimized methods
class SceneTeamUpdateNotify$Type extends MessageType<SceneTeamUpdateNotify> {
    constructor() {
        super("SceneTeamUpdateNotify", [
            { no: 1, name: "scene_team_avatar_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SceneTeamAvatar },
            { no: 3, name: "is_in_mp", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SceneTeamUpdateNotify>): SceneTeamUpdateNotify {
        const message = { sceneTeamAvatarList: [], isInMp: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SceneTeamUpdateNotify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneTeamUpdateNotify): SceneTeamUpdateNotify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated SceneTeamAvatar scene_team_avatar_list */ 1:
                    message.sceneTeamAvatarList.push(SceneTeamAvatar.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool is_in_mp */ 3:
                    message.isInMp = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SceneTeamUpdateNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated SceneTeamAvatar scene_team_avatar_list = 1; */
        for (let i = 0; i < message.sceneTeamAvatarList.length; i++)
            SceneTeamAvatar.internalBinaryWrite(message.sceneTeamAvatarList[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool is_in_mp = 3; */
        if (message.isInMp !== false)
            writer.tag(3, WireType.Varint).bool(message.isInMp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message SceneTeamUpdateNotify
 */
export const SceneTeamUpdateNotify = new SceneTeamUpdateNotify$Type();
