// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "SceneReliquaryInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message SceneReliquaryInfo
 */
export interface SceneReliquaryInfo {
    /**
     * @generated from protobuf field: uint32 item_id = 1;
     */
    itemId: number;
    /**
     * @generated from protobuf field: uint64 guid = 2;
     */
    guid: bigint;
    /**
     * @generated from protobuf field: uint32 level = 3;
     */
    level: number;
    /**
     * @generated from protobuf field: uint32 promote_level = 4;
     */
    promoteLevel: number;
}
declare class SceneReliquaryInfo$Type extends MessageType<SceneReliquaryInfo> {
    constructor();
    create(value?: PartialMessage<SceneReliquaryInfo>): SceneReliquaryInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneReliquaryInfo): SceneReliquaryInfo;
    internalBinaryWrite(message: SceneReliquaryInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message SceneReliquaryInfo
 */
export declare const SceneReliquaryInfo: SceneReliquaryInfo$Type;
export {};
