// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "ScenePlayerInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { OnlinePlayerInfo } from "./OnlinePlayerInfo";
/**
 * @generated from protobuf message ScenePlayerInfo
 */
export interface ScenePlayerInfo {
    /**
     * @generated from protobuf field: uint32 uid = 1;
     */
    uid: number;
    /**
     * @generated from protobuf field: uint32 peer_id = 2;
     */
    peerId: number;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: bool is_connected = 4;
     */
    isConnected: boolean;
    /**
     * @generated from protobuf field: uint32 scene_id = 5;
     */
    sceneId: number;
    /**
     * @generated from protobuf field: OnlinePlayerInfo online_player_info = 6;
     */
    onlinePlayerInfo?: OnlinePlayerInfo;
}
declare class ScenePlayerInfo$Type extends MessageType<ScenePlayerInfo> {
    constructor();
    create(value?: PartialMessage<ScenePlayerInfo>): ScenePlayerInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScenePlayerInfo): ScenePlayerInfo;
    internalBinaryWrite(message: ScenePlayerInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message ScenePlayerInfo
 */
export declare const ScenePlayerInfo: ScenePlayerInfo$Type;
export {};
