// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "SceneAvatarInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { AvatarExcelInfo } from "./AvatarExcelInfo";
import { CurVehicleInfo } from "./CurVehicleInfo";
import { ServerBuff } from "./ServerBuff";
import { SceneReliquaryInfo } from "./SceneReliquaryInfo";
import { SceneWeaponInfo } from "./SceneWeaponInfo";
/**
 * @generated from protobuf message SceneAvatarInfo
 */
export interface SceneAvatarInfo {
    /**
     * @generated from protobuf field: uint32 uid = 1;
     */
    uid: number;
    /**
     * @generated from protobuf field: uint32 avatar_id = 2;
     */
    avatarId: number;
    /**
     * @generated from protobuf field: uint64 guid = 3;
     */
    guid: bigint;
    /**
     * @generated from protobuf field: uint32 peer_id = 4;
     */
    peerId: number;
    /**
     * @generated from protobuf field: repeated uint32 equip_id_list = 5;
     */
    equipIdList: number[];
    /**
     * @generated from protobuf field: uint32 skill_depot_id = 6;
     */
    skillDepotId: number;
    /**
     * @generated from protobuf field: repeated uint32 talent_id_list = 7;
     */
    talentIdList: number[];
    /**
     * @generated from protobuf field: SceneWeaponInfo weapon = 8;
     */
    weapon?: SceneWeaponInfo;
    /**
     * @generated from protobuf field: repeated SceneReliquaryInfo reliquary_list = 9;
     */
    reliquaryList: SceneReliquaryInfo[];
    /**
     * @generated from protobuf field: uint32 core_proud_skill_level = 11;
     */
    coreProudSkillLevel: number;
    /**
     * @generated from protobuf field: repeated uint32 inherent_proud_skill_list = 12;
     */
    inherentProudSkillList: number[];
    /**
     * @generated from protobuf field: map<uint32, uint32> skill_level_map = 13;
     */
    skillLevelMap: {
        [key: number]: number;
    };
    /**
     * @generated from protobuf field: map<uint32, uint32> proud_skill_extra_level_map = 14;
     */
    proudSkillExtraLevelMap: {
        [key: number]: number;
    };
    /**
     * @generated from protobuf field: repeated ServerBuff server_buff_list = 15;
     */
    serverBuffList: ServerBuff[];
    /**
     * @generated from protobuf field: repeated uint32 team_resonance_list = 16;
     */
    teamResonanceList: number[];
    /**
     * @generated from protobuf field: uint32 wearing_flycloak_id = 17;
     */
    wearingFlycloakId: number;
    /**
     * @generated from protobuf field: uint32 born_time = 18;
     */
    bornTime: number;
    /**
     * @generated from protobuf field: uint32 costume_id = 19;
     */
    costumeId: number;
    /**
     * @generated from protobuf field: CurVehicleInfo cur_vehicle_info = 20;
     */
    curVehicleInfo?: CurVehicleInfo;
    /**
     * @generated from protobuf field: AvatarExcelInfo excel_info = 21;
     */
    excelInfo?: AvatarExcelInfo;
    /**
     * @generated from protobuf field: uint32 anim_hash = 22;
     */
    animHash: number;
}
declare class SceneAvatarInfo$Type extends MessageType<SceneAvatarInfo> {
    constructor();
    create(value?: PartialMessage<SceneAvatarInfo>): SceneAvatarInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneAvatarInfo): SceneAvatarInfo;
    private binaryReadMap13;
    private binaryReadMap14;
    internalBinaryWrite(message: SceneAvatarInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message SceneAvatarInfo
 */
export declare const SceneAvatarInfo: SceneAvatarInfo$Type;
export {};
