// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "SceneEntityAppearNotify.proto" (syntax proto3),// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { VisionType } from "./VisionType";
import { SceneEntityInfo } from "./SceneEntityInfo";
/**
 * @generated from protobuf enum SceneEntityAppearNotify.CmdId
 */
export var SceneEntityAppearNotify_CmdId;
(function (SceneEntityAppearNotify_CmdId) {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    SceneEntityAppearNotify_CmdId[SceneEntityAppearNotify_CmdId["NONE"] = 0] = "NONE";
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    SceneEntityAppearNotify_CmdId[SceneEntityAppearNotify_CmdId["ENET_CHANNEL_ID"] = 0] = "ENET_CHANNEL_ID";
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    SceneEntityAppearNotify_CmdId[SceneEntityAppearNotify_CmdId["ENET_IS_RELIABLE"] = 1] = "ENET_IS_RELIABLE";
    /**
     * @generated from protobuf enum value: CMD_ID = 201;
     */
    SceneEntityAppearNotify_CmdId[SceneEntityAppearNotify_CmdId["CMD_ID"] = 201] = "CMD_ID";
})(SceneEntityAppearNotify_CmdId || (SceneEntityAppearNotify_CmdId = {}));
// @generated message type with reflection information, may provide speed optimized methods
class SceneEntityAppearNotify$Type extends MessageType {
    constructor() {
        super("SceneEntityAppearNotify", [
            { no: 1, name: "entity_list", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SceneEntityInfo },
            { no: 2, name: "appear_type", kind: "enum", T: () => ["VisionType", VisionType] },
            { no: 3, name: "param", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value) {
        const message = { entityList: [], appearType: 0, param: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated SceneEntityInfo entity_list */ 1:
                    message.entityList.push(SceneEntityInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* VisionType appear_type */ 2:
                    message.appearType = reader.int32();
                    break;
                case /* uint32 param */ 3:
                    message.param = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated SceneEntityInfo entity_list = 1; */
        for (let i = 0; i < message.entityList.length; i++)
            SceneEntityInfo.internalBinaryWrite(message.entityList[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* VisionType appear_type = 2; */
        if (message.appearType !== 0)
            writer.tag(2, WireType.Varint).int32(message.appearType);
        /* uint32 param = 3; */
        if (message.param !== 0)
            writer.tag(3, WireType.Varint).uint32(message.param);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message SceneEntityAppearNotify
 */
export const SceneEntityAppearNotify = new SceneEntityAppearNotify$Type();
