// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "SceneTimeNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message SceneTimeNotify
 */
export interface SceneTimeNotify {
    /**
     * @generated from protobuf field: uint32 scene_id = 1;
     */
    sceneId: number;
    /**
     * @generated from protobuf field: bool is_paused = 2;
     */
    isPaused: boolean;
    /**
     * @generated from protobuf field: uint64 scene_time = 3;
     */
    sceneTime: bigint;
}
/**
 * @generated from protobuf enum SceneTimeNotify.CmdId
 */
export declare enum SceneTimeNotify_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 230;
     */
    CMD_ID = 230
}
declare class SceneTimeNotify$Type extends MessageType<SceneTimeNotify> {
    constructor();
    create(value?: PartialMessage<SceneTimeNotify>): SceneTimeNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneTimeNotify): SceneTimeNotify;
    internalBinaryWrite(message: SceneTimeNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message SceneTimeNotify
 */
export declare const SceneTimeNotify: SceneTimeNotify$Type;
export {};
