// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "ScreenInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ScreenInfo
 */
export interface ScreenInfo {
    /**
     * @generated from protobuf field: uint32 live_id = 1;
     */
    liveId: number;
    /**
     * @generated from protobuf field: uint32 projector_entity_id = 2;
     */
    projectorEntityId: number;
}
declare class ScreenInfo$Type extends MessageType<ScreenInfo> {
    constructor();
    create(value?: PartialMessage<ScreenInfo>): ScreenInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScreenInfo): ScreenInfo;
    internalBinaryWrite(message: ScreenInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message ScreenInfo
 */
export declare const ScreenInfo: ScreenInfo$Type;
export {};
