// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "ScreenInfo.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ScreenInfo
 */
export interface ScreenInfo {
    /**
     * @generated from protobuf field: uint32 live_id = 1;
     */
    liveId: number;
    /**
     * @generated from protobuf field: uint32 projector_entity_id = 2;
     */
    projectorEntityId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ScreenInfo$Type extends MessageType<ScreenInfo> {
    constructor() {
        super("ScreenInfo", [
            { no: 1, name: "live_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "projector_entity_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ScreenInfo>): ScreenInfo {
        const message = { liveId: 0, projectorEntityId: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ScreenInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScreenInfo): ScreenInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 live_id */ 1:
                    message.liveId = reader.uint32();
                    break;
                case /* uint32 projector_entity_id */ 2:
                    message.projectorEntityId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScreenInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 live_id = 1; */
        if (message.liveId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.liveId);
        /* uint32 projector_entity_id = 2; */
        if (message.projectorEntityId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.projectorEntityId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ScreenInfo
 */
export const ScreenInfo = new ScreenInfo$Type();
