"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StoreType = void 0;
// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_typescript,// @generated from protobuf file "StoreType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum StoreType
 */
var StoreType;
(function (StoreType) {
    /**
     * @generated from protobuf enum value: STORE_NONE = 0;
     */
    StoreType[StoreType["STORE_NONE"] = 0] = "STORE_NONE";
    /**
     * @generated from protobuf enum value: STORE_PACK = 1;
     */
    StoreType[StoreType["STORE_PACK"] = 1] = "STORE_PACK";
    /**
     * @generated from protobuf enum value: STORE_DEPOT = 2;
     */
    StoreType[StoreType["STORE_DEPOT"] = 2] = "STORE_DEPOT";
})(StoreType = exports.StoreType || (exports.StoreType = {}));
