// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "StoreWeightLimitNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StoreType } from "./StoreType";
/**
 * @generated from protobuf message StoreWeightLimitNotify
 */
export interface StoreWeightLimitNotify {
    /**
     * @generated from protobuf field: StoreType store_type = 1;
     */
    storeType: StoreType;
    /**
     * @generated from protobuf field: uint32 weight_limit = 3;
     */
    weightLimit: number;
    /**
     * @generated from protobuf field: uint32 material_count_limit = 4;
     */
    materialCountLimit: number;
    /**
     * @generated from protobuf field: uint32 weapon_count_limit = 5;
     */
    weaponCountLimit: number;
    /**
     * @generated from protobuf field: uint32 reliquary_count_limit = 6;
     */
    reliquaryCountLimit: number;
    /**
     * @generated from protobuf field: uint32 furniture_count_limit = 7;
     */
    furnitureCountLimit: number;
}
/**
 * @generated from protobuf enum StoreWeightLimitNotify.CmdId
 */
export declare enum StoreWeightLimitNotify_CmdId {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 618;
     */
    CMD_ID = 618
}
declare class StoreWeightLimitNotify$Type extends MessageType<StoreWeightLimitNotify> {
    constructor();
    create(value?: PartialMessage<StoreWeightLimitNotify>): StoreWeightLimitNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StoreWeightLimitNotify): StoreWeightLimitNotify;
    internalBinaryWrite(message: StoreWeightLimitNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message StoreWeightLimitNotify
 */
export declare const StoreWeightLimitNotify: StoreWeightLimitNotify$Type;
export {};
