// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "Vector.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Vector
 */
export interface Vector {
    /**
     * @generated from protobuf field: float X = 1 [json_name = "X"];
     */
    x: number;
    /**
     * @generated from protobuf field: float Y = 2 [json_name = "Y"];
     */
    y: number;
    /**
     * @generated from protobuf field: float Z = 3 [json_name = "Z"];
     */
    z: number;
}
declare class Vector$Type extends MessageType<Vector> {
    constructor();
    create(value?: PartialMessage<Vector>): Vector;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Vector): Vector;
    internalBinaryWrite(message: Vector, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message Vector
 */
export declare const Vector: Vector$Type;
export {};
