// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "VehicleMember.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message VehicleMember
 */
export interface VehicleMember {
    /**
     * @generated from protobuf field: uint32 uid = 1;
     */
    uid: number;
    /**
     * @generated from protobuf field: uint64 avatar_guid = 2;
     */
    avatarGuid: bigint;
    /**
     * @generated from protobuf field: uint32 pos = 3;
     */
    pos: number;
}
declare class VehicleMember$Type extends MessageType<VehicleMember> {
    constructor();
    create(value?: PartialMessage<VehicleMember>): VehicleMember;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VehicleMember): VehicleMember;
    internalBinaryWrite(message: VehicleMember, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message VehicleMember
 */
export declare const VehicleMember: VehicleMember$Type;
export {};
