// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "VisionType.proto" (syntax proto3),// tslint:disable
/**
 * @generated from protobuf enum VisionType
 */
export declare enum VisionType {
    /**
     * @generated from protobuf enum value: VISION_NONE = 0;
     */
    VISION_NONE = 0,
    /**
     * @generated from protobuf enum value: VISION_MEET = 1;
     */
    VISION_MEET = 1,
    /**
     * @generated from protobuf enum value: VISION_REBORN = 2;
     */
    VISION_REBORN = 2,
    /**
     * @generated from protobuf enum value: VISION_REPLACE = 3;
     */
    VISION_REPLACE = 3,
    /**
     * @generated from protobuf enum value: VISION_WAYPOINT_REBORN = 4;
     */
    VISION_WAYPOINT_REBORN = 4,
    /**
     * @generated from protobuf enum value: VISION_MISS = 5;
     */
    VISION_MISS = 5,
    /**
     * @generated from protobuf enum value: VISION_DIE = 6;
     */
    VISION_DIE = 6,
    /**
     * @generated from protobuf enum value: VISION_GATHER_ESCAPE = 7;
     */
    VISION_GATHER_ESCAPE = 7,
    /**
     * @generated from protobuf enum value: VISION_REFRESH = 8;
     */
    VISION_REFRESH = 8,
    /**
     * @generated from protobuf enum value: VISION_TRANSPORT = 9;
     */
    VISION_TRANSPORT = 9,
    /**
     * @generated from protobuf enum value: VISION_REPLACE_DIE = 10;
     */
    VISION_REPLACE_DIE = 10,
    /**
     * @generated from protobuf enum value: VISION_REPLACE_NO_NOTIFY = 11;
     */
    VISION_REPLACE_NO_NOTIFY = 11,
    /**
     * @generated from protobuf enum value: VISION_BORN = 12;
     */
    VISION_BORN = 12,
    /**
     * @generated from protobuf enum value: VISION_PICKUP = 13;
     */
    VISION_PICKUP = 13,
    /**
     * @generated from protobuf enum value: VISION_REMOVE = 14;
     */
    VISION_REMOVE = 14,
    /**
     * @generated from protobuf enum value: VISION_CHANGE_COSTUME = 15;
     */
    VISION_CHANGE_COSTUME = 15,
    /**
     * @generated from protobuf enum value: VISION_FISH_REFRESH = 16;
     */
    VISION_FISH_REFRESH = 16,
    /**
     * @generated from protobuf enum value: VISION_FISH_BIG_SHOCK = 17;
     */
    VISION_FISH_BIG_SHOCK = 17,
    /**
     * @generated from protobuf enum value: VISION_FISH_QTE_SUCC = 18;
     */
    VISION_FISH_QTE_SUCC = 18
}
