// @generated by protobuf-ts 2.4.0 with parameter generate_dependencies,output_javascript,// @generated from protobuf file "WorldPlayerInfoNotify.proto" (syntax proto3),// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { OnlinePlayerInfo } from "./OnlinePlayerInfo";
/**
 * @generated from protobuf message WorldPlayerInfoNotify
 */
export interface WorldPlayerInfoNotify {
    /**
     * @generated from protobuf field: repeated OnlinePlayerInfo player_info_list = 1;
     */
    playerInfoList: OnlinePlayerInfo[];
    /**
     * @generated from protobuf field: repeated uint32 player_uid_list = 2;
     */
    playerUidList: number[];
}
/**
 * @generated from protobuf enum WorldPlayerInfoNotify.CmdId
 */
export declare enum WorldPlayerInfoNotify_CmdId {
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    ENET_CHANNEL_ID = 0,
    /**
     * @generated from protobuf enum value: ENET_CHANNEL_ID = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    ENET_IS_RELIABLE = 1,
    /**
     * @generated from protobuf enum value: ENET_IS_RELIABLE = 1;
     */
    IS_ALLOW_CLIENT = 1,
    /**
     * @generated from protobuf enum value: CMD_ID = 3109;
     */
    CMD_ID = 3109
}
declare class WorldPlayerInfoNotify$Type extends MessageType<WorldPlayerInfoNotify> {
    constructor();
    create(value?: PartialMessage<WorldPlayerInfoNotify>): WorldPlayerInfoNotify;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorldPlayerInfoNotify): WorldPlayerInfoNotify;
    internalBinaryWrite(message: WorldPlayerInfoNotify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message WorldPlayerInfoNotify
 */
export declare const WorldPlayerInfoNotify: WorldPlayerInfoNotify$Type;
export {};
